version: "3.8"

services:
  api:
    image: python:3.11-slim
    container_name: dashboard-api
    working_dir: /app
    volumes:
      - ./api:/app
      - ./data/runs:/data/runs
    command: >
      sh -c "pip install fastapi uvicorn &&
        uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"


  web:
    image: nginx:alpine
    container_name: dashboard-web
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
